annotator_name: "gemma-3-27b-it-base"
model_name: "google/gemma-3-27b-it"
num_gpus: 2
max_model_len: null
use_personas: false
num_personas: 8
subtask1:
  data_path: "./data/subtask1/{split}"
  save_dir: "./annotations/st1/{split}"
  languages:
    - amh
    - arb
    - ben
    - mya
    - eng
    - deu
    - hau
    - hin
    - ita
    - khm
    - nep
    - ori
    - fas
    - pol
    - pan
    - rus
    - spa
    - swa
    - tel
    - tur
    - urd
    - zho
  class_labels:
    - "Yes"
    - "No"
    - "yes"
    - "no"
  conf_labels: null
  sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text is polarizing. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token."
  user_prompt: "Input text: {INPUT_TEXT}\nIs polarizing (yes/no):"

subtask2:
  data_path: "./data/subtask2/{split}"
  save_dir: "./annotations/st2/{split}"
  languages:
    - amh
    - arb
    - ben
    - deu
    - eng
    - fas
    - hau
    - hin
    - ita
    - khm
    - mya
    - nep
    - ori
    - pan
    - pol
    - rus
    - spa
    - swa
    - tel
    - tur
    - urd
    - zho
  class_labels:
    - "Yes"
    - "No"
    - "yes"
    - "no"
  conf_labels: null
  pol_sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text is politically/ideologically polarizing. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token.\n\nPolitical/ideological polarization guidelines: This type of extremism focuses on division, intolerance, and conflict between political parties and followers. Political polarization refers to political beliefs and affiliations becoming more extreme. People may identify more strongly with their political party, leading to deeper divides and a reduced willingness to compromise. It broadens ideological differences between political groups."
  pol_user_prompt: "Input text: {INPUT_TEXT}\nIs politically/ideologically polarizing (yes/no):"
  race_sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text is racially/ethnically polarizing. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token.\n\nRacial/ethnic polarization guidelines: This type of polarization focuses on ethnic identity or racial origin and incites division, intolerance, and conflict between ethnic groups or races. This type of polarization arises when individuals identify more strongly with their own racial or ethnic group, leading to increased separation, mistrust, or conflict with individuals from other groups."
  race_user_prompt: "Input text: {INPUT_TEXT}\nIs racially/ethnically polarizing (yes/no):"
  rel_sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text is religiously polarizing. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token.\n\nReligious polarization guidelines: This type of polarization focuses on religious identity and incites division, intolerance, and conflict between religious followers."
  rel_user_prompt: "Input text: {INPUT_TEXT}\nIs religiously polarizing (yes/no):"
  gen_sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text is polarizing based on gender/sexual orientation. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token.\n\nGender/sexual orientation polarization guidlines: Gender polarization: This type of polarization refers to the exclusion, discrimination, and marginalization of individuals based on their gender. Sexual orientation polarization: This refers to the increasing division and distinction between different sexual orientations within society, often leading to heightened tensions, misunderstandings, conflicts, or marginalization among various groups."
  gen_user_prompt: "Input text: {INPUT_TEXT}\nIs polarizing based on gender/sexual orientation (yes/no):"
  other_sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text is polarizing based on something other than politics/ideology, race/ethnicity, religion, or gender/sexual orientation. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token.\n\nOther polarization guidelines: polarization texts targeting other groups/identities such as economy, technology, media, polarization, etc."
  other_user_prompt: "Input text: {INPUT_TEXT}\nIs polarizing for a reason other than politics/ideology, race/ethnicity, religion, or gender/sexual orientation"
    
subtask3:
  data_path: "./data/subtask3/{split}"
  save_dir: "./annotations/st3/{split}"
  languages:
    - amh
    - arb
    - ben
    - deu
    - eng
    - fas
    - hau
    - hin
    - khm
    - nep
    - ori
    - pan
    - spa
    - swa
    - tel
    - tur
    - urd
    - zho
  class_labels:
    - "Yes"
    - "No"
    - "yes"
    - "no"
  conf_labels: null
  stereo_sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text exhibits stereotyping AND is polarizing. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token.\n\nStereotype guidelines: Stereotype: This manifestation occurs when a message generalizes certain characteristics of individuals to all members of a group, ignoring individual differences. Stereotypes simplify complex personalities into one-size-fits-all representations."
  stereo_user_prompt: "Input text: {INPUT_TEXT}\nExhibits stereotyping AND is polarizing (yes/no):"
  vil_sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text exhibits vilification AND is polarizing. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token.\n\nVilification guidelines: Vilification appears when a text defames or demonizes a particular group, person, or entity, often inciting fear through exaggeration, misrepresentation, or biased framing that portrays the subject in a harmful or negative light."
  vil_user_prompt: "Input text: {INPUT_TEXT}\nExhibits vilification AND is polarizing (yes/no):"
  dehum_sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text exhibits dehumanization AND is polarizing. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token.\n\nDehumanization guidelines: This occurs when language strips a group or individual of human qualities or dignity, often by comparing them to animals, machines, or objects, or by otherwise denying their humanity and individuality."
  dehum_user_prompt: "Input text: {INPUT_TEXT}\nExhibits dehumanization AND is polarizing (yes/no):"
  ela_sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text exhibits extreme language and absolutism AND is polarizing. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token.\n\nExtreme language and absolutism guidelines: This manifestation involves the use of extreme or absolutist language that reflects polarized attitudes, such as words like “always,” “never,” “worst,” or “best.” It often presents issues in dichotomous terms such as “us vs. them” or “right vs. wrong.”"
  ela_user_prompt: "Input text: {INPUT_TEXT}\nExhibits extreme language and absolutism AND is polarizing (yes/no):"
  leu_sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text exhibits a lack of empathy and understanding AND is polarizing. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token.\n\nLack of empathy or understanding guidelines: This occurs when the text shows no empathy or understanding for others’ perspectives or experiences. It may involve marginalizing alternative viewpoints or refusing to understand or relate to them."
  leu_user_prompt: "Input text: {INPUT_TEXT}\nExhibits a lack of empathy or understanding AND is polarizing (yes/no):"
  inv_sys_prompt: "You are a highly accurate polarization detection system. You will be provided with a piece of text in the {LANGUAGE} language and you must respond in English with either 'yes' or 'no' as to whether the provided text exhibits invalidation AND is polarizing. You must respond ONLY 'yes' or 'no' and terminate your response immediately after with the end of generation token.\n\nInvalidation guidelines: Invalidation appears when a text denies or rejects the identity or existence of certain people or groups, dismissing their legitimacy or right to exist."
  inv_user_prompt: "Input text {INPUT_TEXT}\nExhibits invalidation AND is polarizing (yes/no):"

